### ISSUE TITLE
Verify if this line affects the outcome in TAS

### ISSUE THREAD

**Issue by Zerpet** [rabbitmq/support-tools#42]
https://github.com/rabbitmq/support-tools/blob/4592a8d144855aae24bae73f636c9c95fd93b59f/scripts/rabbitmq-collect-env#L210-L216

**Comment by lukebakken** [comment]
Is there something you observed? The env file is sourced to get the value of RABBITMQ_LOG_BASE, if I remember correctly.

**Comment by Zerpet** [comment]
We observed this warning in a customer environment in a call earlier today. It's probably that the location within TAS context has changed.

**Comment by lukebakken** [comment]
> We observed this warning in a customer environment in a call earlier today

Huh, why would `RABBITMQ_ENV` be set to a file that doesn't exist, or has zero bytes? Is it common for that file to be empty in TAS?

**Comment by Zerpet** [comment]
I suspect the variable was not set at all, probably because the location of this binary has changed in recent versions of the Tile.

**Comment by lukebakken** [comment]
OK, or these default values aren't correct anymore -

https://github.com/rabbitmq/support-tools/blob/4592a8d144855aae24bae73f636c9c95fd93b59f/scripts/rabbitmq-collect-env#L178-L182

**Comment by Zerpet** [comment]
I think the problem is exactly there, the `privbin` is not a thing anymore, nowadays it should be `sbin`. I will give this a go on Monday.
